export const COLOR_FETCH_SUCCESS = 'COLOR_FETCH_SUCCESS';
export const COLOR_FETCH_FAIL = 'COLOR_FETCH_FAIL';

export const AC_INPUT_CHANGE = 'AC_INPUT_CHANGE';
export const AC_SET_ITEMS = 'AC_SET_ITEMS';
export const AC_SET_FILTERED_ITEMS = 'AC_SET_FILTERED_ITEMS';
export const AC_SET_FOCUS = 'AC_SET_FOCUS';
export const AC_SELECT_ITEM = 'AC_SELECT_ITEM';
export const AC_CLICK_ITEM = 'AC_CLICK_ITEM';
export const AC_CLICK_ITEM_DONE = 'AC_CLICK_ITEM_DONE';
